### ISSUE TITLE
Multiple ContextLoader* definitions

### ISSUE THREAD

**Issue by manojsharma20** [eugenp/REST-With-Spring#74] opened 2016-12-26 12:12 UTC
Hi,

I am getting ` Cannot initialize context because there is already a root application context present - check whether you have multiple ContextLoader* definitions in your web.xml!` error when i have added boot configuration in UmApp class.

earlier it was returning Roles, and also if run it from Spring boot, i am getting empty array.

**Comment by eugenp** [comment] 2016-12-26 12:28
Hey @manojsharma20 - what's the exact branch/lesson you're trying to run?
Cheers, 
Eugen.

**Comment by manojsharma20** [comment] 2016-12-26 12:37
Yes.

I am able to run the rest api without boot. Once i have added Spring boot umapp class as you have mentioned in your tutorials, then spring boot does not show output instead it showing empty array like [] square brackets. If i run the same project on tomcat then tomcat won't start and showing above multiple context error.

**Comment by manojsharma20** [comment] 2016-12-26 12:37
If i comment entire code inside UmApp class then again it start as normal and showing results using tomcat and cargo.

**Comment by manojsharma20** [comment] 2016-12-26 12:48
Rest API M1 lession 4

**Comment by manojsharma20** [comment] 2016-12-27 05:56
Hi, Eugen you did not reply. What could be the issue.

**Comment by eugenp** [comment] 2016-12-27 08:35
Hey Manoj - I've been out during Christmas, that why I didn't reply. 
So, I just ran this lesson: https://github.com/eugenp/REST-With-Spring/tree/module1/m1-lesson4
Both as a Boot project as well as deployed in a Tomcat 8.0.39 server - both work fine. 
So, the first thing I'd suggest here is - make sure you're on the right branch, running the right lesson and of course - in this case, first run the finished version and then try to reproduce that yourself, from the -start version. 

Let me know if - when you run this lesson - you're still seeing the problem. 
Cheers, 
Eugen.

**Comment by manojsharma20** [comment] 2016-12-27 09:50
What is the difference between two branch start and without start.

**Comment by eugenp** [comment] 2016-12-27 10:20
The main difference is - the -start project is the start point of the video (if you want to implement things along with the video - which I recommend all students do). 
The one without start is the finished codebase of the lesson, if you want to jump right to that. 

Hope that clears things up. Cheers, 
Eugen.

**Comment by manojsharma20** [comment] 2016-12-28 06:44
Hi,

I came to know that i have to disable web.xml thats why i am getting error. I have i have disabled it, but i am getting another error that is:

` .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v1.4.0.RELEASE)

12:11:51.986 [main] INFO  c.b.u.p.s.MyApplicationContextInitializer - The active profiles are: null
12:11:51.994 [main] WARN  o.s.boot.SpringApplication - Error handling failed (ApplicationEventMulticaster not initialized - call 'refresh' before multicasting events via the context: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@9d5509a: startup date [Thu Jan 01 05:30:00 IST 1970]; root of context hierarchy)
12:11:52.064 [main] ERROR o.s.boot.SpringApplication - Application startup failed
java.lang.NullPointerException: null
	at com.baeldung.um.persistence.setup.MyApplicationContextInitializer.initialize(MyApplicationContextInitializer.java:27)
	at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:633)
	at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:347)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:311)
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:134)
	at com.baeldung.um.spring.UmApp.main(UmApp.java:53)`

**Comment by eugenp** [comment] 2016-12-28 07:27
Before we go on, let's first clear up the main question - are you running this module: https://github.com/eugenp/REST-With-Spring/tree/module1/m1-lesson4 as a Boot app?
I asked before but never got the answer from you. 
Cheers, 
Eugen.

**Comment by manojsharma20** [comment] 2016-12-28 07:50
Yes, I have tried above and running properly. My issue with its start.

**Comment by eugenp** [comment] 2016-12-28 08:04
OK, one other note then. The -start isn't supposed to run exactly as it is. These start modules represent the start point for the lesson, so you can build along with the video. 
So - did you go through the full lesson, start to finish and made all the modifications shown there?
Cheers, 
Eugen.

**Comment by manojsharma20** [comment] 2016-12-28 08:17
Yes, I have tried my level best. If i run that module without boot, then i am able to get the results. When i converted it into the boot and disable the web.xml to web.bkp.xml then i am only getting that error.

**Comment by eugenp** [comment] 2016-12-28 08:44
I see; I'll try to reproduce it and get back to you here. 
Cheers, 
Eugen.

**Comment by eugenp** [comment] 2016-12-31 11:34
Hey @manojsharma20 - quick update here. I was able to reproduce a problem - after removing the web.xml, the Boot deployment works fine, but there is a problem with the stand-alone deployment. Looking into it. 
Cheers, 
Eugen.

**Comment by manojsharma20** [comment] 2017-01-23 06:50
Is there any update ?

**Comment by eugenp** [comment] 2017-01-25 08:13
Hey @manojsharma20 - yes, the issue should be fixed. Can you do a pull and try to deploy the lesson?
Cheers, 
Eugen.

**Comment by zhenyanghua** [comment] 2017-05-18 02:01
@eugenp I have the same issue @manojsharma20 describes here. I can successfully run the *user-management-parent-m1-l4* if I checkout from the repo. However, using the version that I started from zero (trying to understand the codebase, so I followed the codebase, created a duplicate, only with a few dependency update and unify some service method naming, it works with the XML config, however, returns empty array when switching to use the UmApp.java. This is my update-to-date [repo](https://github.com/zhenyanghua/user-management). Could you share some tips of trouble-shooting the empty array, such as where to start? Thanks!

**Comment by zhenyanghua** [comment] 2017-05-18 02:41
@manojsharma20 @eugenp I found the difference that caused this issue. It was caused by the `SecuritySetup.java` Profile change. It returns empty array is because the profile `production` used in the web.xml is no longer referenced in the Java config. Thus, the annotated SecuritySetup class was not used as the profile for the application to run on. @manojsharma20, you need to remove the profile annotation from the SecuritySetup class or apply it to the application before run it. Here is what I did to fix this:

`Profiles.java`
```java
public final class Profiles {
    
    public static final String DEVELOPMENT = "development";
```

`SecuritySetup.java`
```java
@Component
@Profile(Profiles.DEVELOPMENT)
public class SecuritySetup implements ApplicationListener<ContextRefreshedEvent> {
```

`UmApp.java`
```java
public static void main(final String... args) {
        SpringApplication app = new SpringApplication(UmApp.class);
        app.setAdditionalProfiles(Profiles.DEVELOPMENT);
        app.run(args);
    }
```

**Comment by eugenp** [comment] 2017-05-19 10:42
Hey guys - one quick note here. 
When you implement lesson 4 - are you starting with the m1-lesson4-start module?
Meaning - this one: https://github.com/eugenp/REST-With-Spring/tree/module1/m1-lesson4-start

That's the place to start when you do the work on this lesson. 
Cheers, 
Eugen.

**Comment by zhenyanghua** [comment] 2017-05-19 12:53
The repo works. However, there is a jump between the m1-lesson3 codebase and m1-lesson4-start code base, that is how I missed the changes of Profile which caused the reset api to return empty collection, once I corrected it, it works again.

**Comment by eugenp** [comment] 2017-05-20 11:57
Well, each lesson has a start point and an end point. So - when you go through the lesson and you want to follow along with the video and go through the implementation, my suggestion is to always start from the starting point. 
There definitely are some small differences between separate lessons - that's by design. Basically, the idea is to have a well-prepared starting point where you can focus just on the main topic in the lesson, not on other setup related things. That's why the starting point has some preparations done already. 

So - let me know if - starting from this starting point - you're still running into problems?

**Comment by zhenyanghua** [comment] 2017-05-20 12:44
That's makes sense now, all things work for me, thanks!

Zhenyang

**Comment by eugenp** [comment] 2017-05-21 19:25
Sounds good - I'm glad everything's working as expected. 
Cheers, 
Eugen.

**Closed by eugenp** 2017-05-21 19:25 UTC
